export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const ADD_POSTS_SUCCESS = 'ADD_POSTS_SUCCESS';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES_SUCCESS = 'UPDATE_LIKES_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
