export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
